### ISSUE TITLE
lots of ECONNRESET issues

### ISSUE THREAD

**Issue by mitchcapper** [ocilo/skype-http#103]
Looking at the logs it seems that in april this would happen at a maximum a few times a day (and on average maybe once every few days)
"An error happened while processing the polled messages": 
Error: read ECONNRESET
        at exports._errnoException (util.js:1050:11)
        at TLSWrap.onread (net.js:581:26)

However recently it has become near constant.  Upon connect it can almost certainly occur (sometimes during the login itself).  Reconnecting right away using the new token also fails falling back to user/pass.

Using a proxy through the same server the web client does not exhibit similar behavior (all poll requests are successful).

**Comment by n3tman** [comment]
Same thing for me. All bots became almost unusable :(

**Comment by n3tman** [comment]
So after trying to solve these ECONNRESET issues I decided to switch to Microsoft Bot API and it works without a single error. Couldn't be happier with it, and it's all free too. If you only need Skype, you won't need to switch to Azure, just remove Web Chat and add Skype channel. 

Create your bot here:
https://dev.botframework.com/bots/new

All I needed to do is save address of each channel (used typicode/lowdb for this task):
https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-proactive-messages

**Comment by mitchcapper** [comment]
Unfortunately bots can't work with existing users or share a user account (for example to only handle certain messages directly).  For others though it may be a good fit.  I am guessing the issue came about when they did the revision for read receipts.     Unfortunately, I have yet to find a full solution to this bug.

**Comment by mitchcapper** [comment]
Alright so after updating everything fully clearing all state data (this seemed to cause an issue) I was able to avoid this problem and get good connections again.   May want to use PR #112 to assist with running latest version of libs.

**Comment by mitchcapper** [comment]
Sadly this issue still persists.   Will have to try proxying some connections to detect the difference.  Not as bad as before but still get a few a day.
