### ISSUE TITLE
skpy.core.SkypeAuthException: Token file has expired

### ISSUE THREAD

**Issue by YafengWangGitHub** [ocilo/skype-http#119]
Hi everyone, I am working with Skpy, I have used following code for two months, but this morning it suddenly returns this error
########################################################################
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\skpy\main.py", line 67, in init
self.conn.readToken()
File "C:\ProgramData\Anaconda3\lib\site-packages\skpy\conn.py", line 301, in readToken
raise SkypeAuthException("Token file has expired")
skpy.core.SkypeAuthException: Token file has expired
########################################################################
Here is my code:

from skpy import Skype
import time

i = 0
j = 0
k = 0

Skype('xxxx', 'xxxx', ".tokens-fred.2")
sk = Skype(tokenFile=".tokens-fred.2")

print(sk.conn)

while True:
        j += 1
        if j>8:
            time.sleep(200)            
        ms = sk.chats["VIP"].getMsgs()
        if len(ms)>= 10:
            print("init..." + str(len(ms)))
        elif len(ms)!=0:
            if i != 0:
                print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
                print(ms)
            i += 1
        else:
            k += 1
            print("checking..." + str(k))

**Comment by YafengWangGitHub** [comment]
problem solved by just change the Skype password
