### ISSUE TITLE
#t -> #ipt; own profile can not be obtained.

### ISSUE THREAD

**Issue by IngwiePhoenix** [ocilo/skype-http#121]
I'm in a bit of a hurry, so here is the gist: `#t` is now `#ipt`. After logging in, this shows up:

```
UnexpectedResult: { body: { status: { code: 40100, text: 'Authentication failed' } } }
    at Object.getSelfProfile (/srv/matrix/skype/node_modules/skype-http/api/get-self-profile.js:39:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.login (/srv/matrix/skype/node_modules/skype-http/login.js:47:21)
    at async Object.connect (/srv/matrix/skype/node_modules/skype-http/connect.js:28:22)
  caused by InvalidDocument: { extra: undefined, missing: Set (19) {'firstname', 'lastname', 'birthday', 'gender', 'language', 'country', 'province', 'city', 'homepage', 'about', 'emails', 'jobtitle', 'phoneMo
bile', 'phoneHome', 'phoneOffice', 'mood', 'richMood', 'avatarUrl', 'username'}, invalid: Map (0) {} } {
  name: 'UnexpectedResult',
  data: { body: { status: [Object] } },
  cause: [InvalidDocument: { extra: undefined, missing: Set (19) {'firstname', 'lastname', 'birthday', 'gender', 'language', 'country', 'province', 'city', 'homepage', 'about', 'emails', 'jobtitle', 'phoneMobi
le', 'phoneHome', 'phoneOffice', 'mood', 'richMood', 'avatarUrl', 'username'}, invalid: Map (0) {} }] {
    name: 'InvalidDocument',
    data: { extra: undefined, missing: [Set], invalid: Map {} },
    message: "{ extra: undefined, missing: Set (19) {'firstname', 'lastname', 'birthday', 'gender', 'language', 'country', 'province', 'city', 'homepage', 'about', 'emails', 'jobtitle', 'phoneMobile', 'phoneHo
me', 'phoneOffice', 'mood', 'richMood', 'avatarUrl', 'username'}, invalid: Map (0) {} }"
  }
}
```

Using this with the Matrix Skype bridge! :)

**Comment by tungd** [comment]
I ran into the same issue. In my case this is because Microsoft decided that this is an "unusual activity" and send the client a different page. Once you verified that it is indeed you, it's `#t` again it works.
